# Generated by Django 3.0.5 on 2022-01-13 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_remove_doctor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('assignedDoctorId', models.PositiveIntegerField(null=True)),
                ('allergy_substance', models.CharField(max_length=100)),
                ('allergy_criticality', models.CharField(choices=[('low', 'low'), ('intermediate', 'intermediate'), ('high', 'high')], default='low', max_length=20)),
                ('problems_list', models.CharField(max_length=100)),
                ('immunization', models.CharField(max_length=100)),
                ('history_procedure', models.CharField(max_length=100)),
                ('diagnostic_results', models.FileField(blank=True, null=True, upload_to='patient_document/')),
                ('past_history_of_illness', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
