# Generated by Django 2.2.12 on 2022-01-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20220113_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrescriptionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('medicationItem', models.CharField(max_length=100)),
                ('frequency', models.PositiveIntegerField()),
                ('dose', models.FloatField()),
                ('doseUnit', models.CharField(max_length=100)),
                ('directionDuration', models.PositiveIntegerField()),
                ('form', models.CharField(max_length=100)),
                ('additionalInstruc', models.CharField(max_length=400)),
                ('substance', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
