# Generated by Django 3.0.5 on 2022-01-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20220113_1935'),
        ('hospital', '0005_auto_20220113_1914'),
    ]

    operations = [
    ]
