# Generated by Django 3.0.5 on 2022-01-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20220114_1556'),
        ('hospital', '0007_auto_20220114_0513'),
        ('hospital', '0007_auto_20220114_0512'),
    ]

    operations = [
    ]
