# Generated by Django 3.2.9 on 2022-01-15 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_merge_20220114_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='authRepeat',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='authValPer',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='dispAmount',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='dispAmountUnits',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='dispDescrip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='dispDurution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='dispInstruc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='orderDateDisc',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='orderDateWritten',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='orderStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Stopped', 'Stopped'), ('Never active', 'Never active'), ('Completed', 'Completed'), ('Obsolete', 'Obsolete'), ('Suspended', 'Suspended'), ('Draft', 'Draft')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='safetyAllowedPer',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='safetyAmount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprescriptiondetails',
            name='safetyDoseUnit',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergy_criticality',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Intermediate', 'Intermediate'), ('High', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprescriptiondetails',
            name='directionDuration',
            field=models.CharField(max_length=200),
        ),
    ]
